README.md, Sources/Redbird/Errors.swift, Sources/Redbird/ExternalTypeConversions.swift, Sources/Redbird/RedbirdExtensions.swift, Tests/ConversionTests.swift
Added .auth convenience command on the client to pass the password to Redis instances requiring a password.
Fixed #2.
=> Authentication simplified

Sources/Redis/Pipeline.swift
Hi, I tried to use v2.0.0-alpha.1.
I found a little difference from README.
I think `Pipeline#enqueue(_, _)` is valid to unify new interfaces each other.
In README.md
```swift
let client = try TCPClient()
let results = try client
.makePipeline()
.enqueue(.set, ["FOO", "BAR"])
.enqueue(.set, ["Hello", "World"])
.enqueue(.get, ["Hello"])
.enqueue(.get, ["FOO"])
.execute()
```
=> Omit keyword of arguments

README.md, Sources/Redis/Command.swift, Tests/RedisTests/LiveTests.swift
This adds the following commands:
[HGET](https://redis.io/commands/hget)
[HSET](https://redis.io/commands/hset)
[HDEL](https://redis.io/commands/hdel)
[HKEYS](https://redis.io/commands/hdel)
[Keys](https://redis.io/commands/keys)
=> Commands for working with hashes and the keys command

Package@swift-4.swift, circle.yml
```
jmsmith@SF-M-JSMITH01 ~/w/B/redis (master)> swift build                                                                                                                 13:56:16
Fetching https://github.com/vapor/core.git
Fetching https://github.com/vapor/node.git
Fetching https://github.com/vapor/sockets.git
Fetching https://github.com/vapor/random.git
Fetching https://github.com/vapor/bits.git
Fetching https://github.com/vapor/debugging.git
Cloning https://github.com/vapor/node.git
Resolving https://github.com/vapor/node.git at 2.1.1
Cloning https://github.com/vapor/random.git
Resolving https://github.com/vapor/random.git at 1.2.0
Cloning https://github.com/vapor/core.git
Resolving https://github.com/vapor/core.git at 2.1.2
Cloning https://github.com/vapor/debugging.git
Resolving …
```
=> Add swift4 support

Sources/Redis/RedisProvider.swift
fix error for example as inside SQLiteProvider:
```
Service Error: No service DatabaseKeyedCache<ConfiguredDatabase<RedisDatabase>> 
has been registered for 'KeyedCache'.
```
=> maybe register the redis for KeyedCache ?

Sources/Redis/Client/Redis+Commands.swift, Sources/Redis/Client/RedisClient.swift, Sources/Redis/Database/RedisDatabase.swift, Tests/RedisTests/RedisDatabaseTests.swift
Pretty much what it says on the tin, this PR:
- Adds a `select(_ database: Int)` command to RedisClient for [SELECT](https://redis.io/commands/select).
- Adds a `database: Int?` field to RedisClientConfig. When set, RedisDatabase now preselects this database before returning the client.
- Adds support for configuring the default database via the Redis URL's path (as seen in other languages).
- Adds some tests.
Resolves #114.
=> Add SELECT command and config conveniences

Sources/Redis/Data/RedisDataConvertible.swift
Useful since some API calls take a `RedisData` but others take a `RedisDataConvertible`
=> `RedisData` should conform to `RedisDataConvertible`

Sources/Redis/Client/Redis+Commands.swift, Tests/RedisTests/RedisTests.swift
Calling `expire` in the current tagged version throws an error: `⚠️ Redis Error: ERR Protocol error: expected '$', got ':'`, which means that the expiration time is expected as a bulk string, not as an integer literal on the wire.
This PR adds a test and fixes the issue.
=> Add failing test for EXPIRE and fix it too

Sources/Redis/Coders/RedisDataDecoder.swift, Tests/RedisTests/RedisDataDecoderTests.swift
Had some crashes occur when the client was trying to parse a null array and you can't create an array of length -1 😅. 
From the [RESP docs](https://redis.io/topics/protocol#resp-arrays):
> ```"*-1\r\n"```
>
> A client library API should return a null object and not an empty Array when Redis replies with a Null Array. This is necessary to distinguish between an empty list and a different condition (for instance the timeout condition of the BLPOP command).
=> Support null arrays

Sources/Redis/Coders/RedisDataDecoder.swift, Sources/Redis/Data/RedisData.swift
- Fixes warning:
```
[WARNING] [Async] [QueueHandler] Read triggered when input queue was empty, ignoring: RedisData
```
- Adds `CustomStringConvertible` conformance to `RedisData`.
=> fix queue handler extra message warning

Sources/Redis/Data/RedisDataConvertible.swift, Tests/LinuxMain.swift, Tests/RedisTests/RedisDataConvertibleTests.swift
This brings `FixedWidthInteger` in alignment with implementation for `Float` and `Double` by providing a fallback conversion from string
=> Fix conversion from RedisData for FixedWidthInteger

Sources/Redis/Client/Commands/Redis+Hash.swift, Tests/RedisTests/RedisTests.swift
There are more hash operations but these are the basic ones.
Also tried to document as much as possible.
=> implemented & added tests for hash operations HSET, HKEYS, HGET, HDEL, HGETALL

Sources/Redis/Coders/RedisDataDecoder.swift
This fixes warnings from the Swift 5 compiler and harmlessly reduces the access level of the two affected functions.
=> Remove redundant access modifiers

Package.swift, Sources/Redis/RedisProvider.swift
Updating to the [provider changes](https://github.com/vapor/vapor/releases/tag/4.0.0-beta.1) in Vapor 4.0 Beta 1, and some related API changes in RedisKit.
=> Update to Vapor and RedisKit 4.0 Beta 1

Package.swift, Sources/Redis/Application+Redis.swift, Sources/Redis/RedisConfiguration.swift
Add support for changing the connection retry timeout from the default of "immediately" to any `NIO.TimeAmount`
This is configurable on the `RedisConfiguration.pool` property:
```swift
// wait 5 seconds while the pool tries to find an available connection before failing commands
app.redis.configuration?.pool.connectionRetryTimeout = .seconds(5)
```
=> add config option for connection retry timeout

Package.swift
Rely on Vapor 4.0.0 release rather than beta version
=> Use swift 4.0.0 instead of 4.0.0-beta in Package

Sources/Redis/RedisConfiguration.swift, Tests/RedisTests/RedisTests.swift
Fix parsing the database index by using `lastPathComponent` to remove trailing `/`
=> Change from using `path` to `lastPathComponent` in RedisConfiguration

Package.swift
Rely on RediStack 1.0.0 full release instead of RC
=> Update from RediStack 1.0.0-rc to 1.0.0

Sources/Redis/Redis+Sessions.swift, Tests/RedisTests/RedisTests.swift
This addresses some semantic issues with the original implementation of `SessionDriver` for Redis in #175.
Two important changes were made to `RedisSessionsDelegate`:
1. `makeNewID` does not prefix the ID with `vrs-` anymore
1. A new `makeKey(for:)` optional method has been added to the protocol to convert an ID to a `RediStack.RedisKey` to customize how the id is represented as a key.
- The default implementation adds the `vrs-` prefix.
In addition, the protocol has seen two quality of life (breaking) changes to the required protocol methods:
1. Their argument labels have been updated to read a bit nicer at call sites, and the `RedisKey` is now passed instead of a `SessionID`
- `redis(_:storeData:forID:)` -> `redis(_:store:with:)`
- `redis(_:fetchDataForID:)` -> `redis(_:fetchDataFor:)` …
=> Change semantics of Redis sessions with key and ID generation

.github/workflows/test.yml, Sources/Redis/Redis+Sessions.swift
This changes the `RedisSessionsDriver` to be generic over the `RedisSessionsDelegate` to drop the performance overhead of the delegate existential.
In general, no one should see a breaking change unless you were passing a `RedisSessionsDelegate` as an existential - as you will see the "RedisSessionsDelegate cannot be passed to a generic context" message
=> Change Sessions driver to be generic

Sources/Redis/Application+Redis.swift
Use the passed-in eventloop when acquiring RedisConnectionPool to prevent triggering a precondition related to ending up in a wrong eventloop (fixes #180, replaces: #183).
=> Use passed-in eventloop when acquiring RedisConnectionPool

Package.swift, Sources/Redis/Redis+Cache.swift, Tests/RedisTests/RedisTests.swift
Add Redis implementation for Vapor's new cache protocol: https://github.com/vapor/vapor/pull/2558
```swift
// Use redis as application cache
app.caches.use(.redis)
```
=> Add cache protocol

Sources/Redis/Redis+Cache.swift, Sources/Redis/RedisClient+Codable.swift, Tests/RedisTests/RedisTests.swift
Adds support for setting an expiration time when using Redis as the Vapor cache via `app.caches.use(.redis)`. See [v4.44.0](https://github.com/vapor/vapor/releases/tag/4.44.0) for more info.
This PR also fixes #187 by adding a function to set an expiration time when setting a key to JSON:
```swift
app.redis.setex("user", toJSON: User(name: "mads"), expirationInSeconds: 10)
```
=> Add support for Vapor `Cache` protocol expiration time

Sources/Redis/Redis+Cache.swift, Tests/RedisTests/RedisTests.swift
It is now possible to specify a custom `Encoder` and `Decoder` to use in place of `JSONEncoder` and `JSONDecoder` for storing and retrieving values cached in Redis via the `Cache` interface.
=> Allow customizing encoding and decoding of RedisCache values

Sources/Redis/RedisConfiguration.swift, Sources/Redis/RedisStorage.swift
This PR adds TLS support to the current stable release of `vapor/redis` (and the underlying RediStack 1.x). There are three behaviour changes (all additive):
- The `RedisConfiguration` struct now has optional `tlsConfiguration` and `tlsHostname` properties.
- The `RedisConfiguration` struct constructors that take URLs now handle `rediss` URLs and will fill out the `tlsConfiguration` and `tlsHostname` properties with default values from the URL.
- If the `tlsConfiguration` and `tlsHostname` properties are set, a custom `ClientBootstrap` will be created when it's time to create a `RedisConnectionPool`, adding a `NIOSSLClientHandler` to the pipeline on top of the ones created by `addBaseRedisHandlers()`. If the properties _aren't_ set, the behaviour is as before. 
This PR allows …
=> Add support for TLS-backed connections to Redis

Package.swift, Sources/Redis/RedisConfiguration.swift
Adds new `onUnexpectedConnectionClose` callback which got added in RediStack 1.4.0
=> Add onUnexpectedConnectionClose
